on:
  # Only run on tag pushes
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install poetry 1.8.5
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.8.5
        python -m poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Install dependencies
      run: python -m poetry install
    - name: Build wheel
      run: python -m poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ha-picnic-api
    permissions:
      id-token: write
    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true